### PR TITLE
Fix up the mod a bit

### PR DESCRIPTION
**Pull request by ghost**
- Change package from `code` to `net.horizonsend.client`
- Change gradle files to use kts
- Add mod menu integration
- Remove unused initializer
- Various minor cleanup

### CODE REVIEW

**Review by SciathGH — APPROVED** [review]
Looks good, Ty Trainboy

**Comment by SciathGH** [comment]
Also, use your merge perms if you want. You're trustworthy

**Comment by SciathGH** [comment]
Just leave a headsup to myself and others if you do, so we can rebase

**Comment by ghost** [comment]
Sounds good

**Comment by SciathGH** [comment]
Thanks again Trainboy

**Pull request merged**
